### ISSUE TITLE
java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by greg-junkietech** [jenkinsci/multi-module-tests-publisher-plugin#2]
I cannot get the plugin working as I hoped.
My job configuration is:
![image](https://cloud.githubusercontent.com/assets/8457529/6751788/8a8cd0dc-cf08-11e4-8cd1-b1d0594da61c.png)

My project at job level has different modules, my first module is called "ADOS RegressionTest 02.Enform" appearing as a top-level directory in the a job workspace, a JUnit report file is generated for each of module in target/surefire-reports/TEST-TestSuites.xml.

The (quite limited) documentation I found on the plugin homepage @ https://wiki.jenkins-ci.org/display/JENKINS/Multi+Module+Tests+Publisher does not help to figure out how I am supposed to configure the plugin.

Here the stacktrace:
Analyzing test results with ProjectResultPublisher...
ERROR: Publisher com.cwctravel.hudson.plugins.multimoduletests.ProjectResultPublisher aborted due to exception
java.lang.NegativeArraySizeException
	at com.cwctravel.hudson.plugins.multimoduletests.junit.io.StringReaderWriter.<init>(StringReaderWriter.java:17)
	at com.cwctravel.hudson.plugins.multimoduletests.junit.io.IOUtil.createReaderWriter(IOUtil.java:11)
	at com.cwctravel.hudson.plugins.multimoduletests.junit.JUnitParser.characters(JUnitParser.java:266)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.characters(AbstractSAXParser.java:538)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:464)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:808)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:119)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1205)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:522)
	at com.cwctravel.hudson.plugins.multimoduletests.junit.JUnitParser.parse(JUnitParser.java:119)
	at com.cwctravel.hudson.plugins.multimoduletests.ProjectResultPublisher$ParseResultCallable.invoke(ProjectResultPublisher.java:240)
	at com.cwctravel.hudson.plugins.multimoduletests.ProjectResultPublisher$ParseResultCallable.invoke(ProjectResultPublisher.java:174)
	at hudson.FilePath.act(FilePath.java:918)
	at hudson.FilePath.act(FilePath.java:896)
	at com.cwctravel.hudson.plugins.multimoduletests.ProjectResultPublisher.perform(ProjectResultPublisher.java:122)
	at hudson.tasks.BuildStepMonitor$3.perform(BuildStepMonitor.java:45)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1040)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
	at hudson.model.Run.execute(Run.java:1770)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:529)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
Finished: FAILURE

**Comment by anichari** [comment]
Hi, I am facing the same issue as @greg-junkietech  is. Have we found a resolution yet?

**Comment by n360speed** [comment]
Based on the error it appears you are missing something in the xml file. The below is an example of what the plugin expects for *.xml files:

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="1" failures="1" hostname="localhost" name="ModuleName" 
   tests="6" time="21.191" timestamp="2016-01-08T20:24:09">
  <properties>
    <property name="property1" value="value1" />
    <property name="property2" value="value2" />
  </properties>
  <!--
      classname depends on your structure
      
      name depends on your test names
      
      if there isn't "skipped", "failure" or "error" testcase, test is considered passed.
      
      You might want to look at JUnitParser.java for how the xml is being parsed.
      
      system-out and system-err location is arbitrary as long as Jenkins can get to it.
      The locations should be unique and should have the actual test run information
      in them. Having this information is useful, as you will be able to view it through
      the Jenkins UI.
  -->
  <testcase classname="com.package.test.module" name="Test_1" time="0">
    <skipped />
  </testcase>
  <testcase classname="com.package.test.module" name="Test_2" time="0">
    <skipped />
  </testcase>
  <testcase classname="com.package.test.module" name="Test_3" time="3.276">
    <system-out><![CDATA[http://localhost/archivedArtifacts/artifact/build_name/1234/junit-logs.zip/ModuleName/com/package/test/module/Test_3/junit.log]]></system-out>
  </testcase>
  <testcase classname="com.package.test.module" name="Test_4" time="3.276">
    <system-out><![CDATA[http://localhost/archivedArtifacts/artifact/build_name/1234/junit-logs.zip/ModuleName/com/package/test/module/Test_4/junit.log]]></system-out>
  </testcase>
  <testcase classname="com.package.test.module" name="Test_5" time="3.276">
    <failure message="Failure message" />
    <system-out><![CDATA[http://localhost/archivedArtifacts/artifact/build_name/1234/junit-logs.zip/ModuleName/com/package/test/module/Test_5/junit.log]]></system-out>
  </testcase>
  <testcase classname="com.package.test.module" name="Test_6" time="3.276">
    <error message="Failure message" />
    <system-out><![CDATA[http://localhost/archivedArtifacts/artifact/build_name/1234/junit-logs.zip/ModuleName/com/package/test/module/Test_6/junit.log]]></system-out>
  </testcase>
  <system-out><![CDATA[http://localhost/archivedArtifacts/artifact/build_name/1234/junit-logs.zip/ModuleName/sysout.log]]></system-out>
  <system-err><![CDATA[http://localhost/archivedArtifacts/artifact/build_name/1234/junit-logs.zip/ModuleName/syserr.log]]></system-err>
</testsuite>
```
I hope this helps!
